blank_issues_enabled: false
contact_links:
  - name: 🏃 Get quick support
    url: https://discord.com/invite/
    about: |
      The Github issues, discussions and the Lemonlight Discord are the primary place to go to get quick support for the Zenith.
      If you have a question or need help, drop by and we can work through your issue together!
